<?php 

$category = $this->category; 

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>EDIT CATEGORY</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>
	<?php 
		require_once 'view/html/header.phtml';
	?>
	<form action="<?php print_r($urlObject->getUrl("Category","save",["id"=>$category->category_id])); ?>" method="POST"> 
		<div class="managediv">
				<span>EDIT CATEGORY</span>
				<button class="button" type="submit">SAVE</button>
				<button class="button"> <a href="<?php print_r($urlObject->getUrl("Category","grid",'',TRUE)); ?> ">CANCEL</a></button>
		</div>

		<div>
			<table class="gridtable"> 
			<tr>
				<th>parent</th>
				<td> <input type="text" name="category[parent]" value=""> </td>
			</tr>
			<tr>
				<th>name</th>
				<td> <input type="text" name="category[name]" value="<?php echo $category->name; ?>"> </td>
			</tr>
			<tr>
				<th>status</th>
				<td>
					<?php $statuses = $category->getTable()->getStatusOptions(); ?>
					<select name="category[status]">

						<?php foreach ($statuses as $key => $value) :?>
						<option value="<?php echo $key; ?>"

										<?php if ($category->getStatusText() == $value) {
											echo "selected";
										}else{
											echo "";
										} ?>

										><?php echo $value; ?>
							
						</option>
					<?php endforeach; ?>

					</select>
				</td>
			</tr>
			<tr>
				<th>discription</th>
				<td> <textarea name="category[discription]"><?php echo $category->discription; ?></textarea> </td>
			</tr>
	</table>

		</div>
		<div class="footer">
			footer
		</div>
	</form>
</body>
</html>