<?php 

$admins = $this->admin;

?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>admin edit</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>
	<form action=" <?php print_r($urlObject->getUrl("admin","save",["id"=>$admins->admin_id])); ?>" method="POST"> 
		<div class="managediv">
			<span>EDIT ADMIN</span>
			<button class="button" type="submit">SAVE</button>
			<button class="button"> <a href=" <?php print_r($urlObject->getUrl("admin","grid",'',TRUE)); ?>">CANCEL</a></button>
		</div>

		<div>
			<table class="gridtable"> 
				<tr> 
					<td>Name</td>
					<td> <input type="text" name="admin[name]" value="<?php echo $admins->name; ?>"> </td> 
				</tr>
				<tr> 
					<td>Email</td>
					<td> <input type="text" name="admin[email]" value="<?php echo $admins->email; ?>"> </td> 
				</tr>
				<tr> 
					<td>Password</td>
					<td> <input type="text" name="admin[password]" value="<?php echo $admins->password; ; ?>"> </td> 
				</tr>
				<tr> 
					<th> status </th>
					<td> 
						<?php $statuses = $admins->getTable()->getStatusOptions(); ?>
						
						<select name="admin[status]">
							<?php foreach ($statuses as $key => $value): ?>
								<option value="<?php echo $key; ?>"

									<?php 
									if ($key == $admins->getStatus()){
										echo "selected";
									}else{
										echo "";
									}
									?>
									> <?php echo $value; ?> </option>
							<?php endforeach; ?>
						</select>
					</td> 
				</table>

			</div>
		</form>
	</body>
	</html>