<?php 

$admins = $this->data['admins'];

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Admin Grid</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>

	<div class="managediv">
		<span class="title">MANAGE ADMIN</span>
		<button class="button">
			<a href="<?php print_r($urlObject->getUrl('admin','add')) ?>">ADD ADMIN</a>
		</button>
	</div>
	<div> 
		<table class="managetable">
			<thead> 
				<tr>
					<th>ADMIN ID</th>
					<th>NAME</th>
					<th>EMAIl</th>
					<th>STATUS</th>
					<th>CREATED AT</th>
					<th>UPDATED AT</th>
					<th>EDIT</th>
					<th>DELETE</th>
				</tr>
			</thead>
			<tbody> 


				<?php if(!$this->admins): ?>
					<tr>
						<td colspan="5">No Record Available.</td>
					</tr>

				<?php else : ?>	
						<?php foreach ($admins as $row): ?>
						<tr>
							<td> <?php echo $row->admin_id; ?> </td>
							<td> <?php echo $row->name; ?> </td>
							<td> <?php echo $row->email; ?> </td>
							<td> <?php echo $row->getStatusText();?> </td>
							<td> <?php echo $row->created_at; ?> </td>
							<td> <?php echo $row->updated_at; ?> </td>
							<td> <a href="<?php print_r($urlObject->getUrl('admin','edit',['id'=>$row->admin_id])) ?>">EDIT</a> </td> 
							<td> <a href="<?php print_r($urlObject->getUrl('admin','delete',['id'=>$row->admin_id])) ?>">DELETE</a> </td> 
						</tr>
					<?php endforeach; ?>

				<?php endif; ?>	
			</tbody> 
		</table>
	</div>

</body>
</html>