<?php 

$medias = $this->medias;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>product_media</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>
<form action=<?php print_r($urlObject->getUrl(NULL,"update")); ?> method="POST"> 

<table  width="100%" cellpadding="20" style="font-size: 30px;" class="header">
	<tr class="yash" >
		<td >MEDIA INFO</td>
		<td ><a href="<?php print_r($urlObject->getUrl(NULL,"add")); ?>" >ADD</a></td>
		<td ><input type="submit" name="submit" value="submit"></td>
		<td ><a href="index.php?c=product&a=grid">BACK</a></td>
	</tr>
</table>


		<table  border="1" width="100%" style="text-align: center;">
			<thead> 
			<tr>
				<th>IMG ID</th>
				<th>PRODUCT ID</th>    
                <th>NAME</th>
                <th>IMAGE</th>
                <th>THUMBNAIL</th>
                <th>SMALL</th>
                <th>BASE IMAGE</th>
                <th>GALLERY</th>
                <th>STATUS</th>
                <th>CREATED AT</th>
                <th>UPDATED AT</th>
                <th>DELETE</th>
			</tr>
			</thead>
			<tbody> 
				<?php if (!$medias) :?>
					<tr>
						<td colspan="12">No Medias Available.</td>
					</tr>
				<?php else: ?>
			<?php foreach ($medias as $value): ?>

			<tr>
				<td><?php echo $value->image_id; ?></td>	
				<td><?php echo $value->product_id; ?></td>	
				<td><?php echo $value->name; ?></td>	

				<td> <img src="view/product_media/temp_folder/<?php echo $value->image; ?>" width="80px" > </td>	

			
				<td> <input type="radio"     name="thumbnail" value="<?php echo $value->image_id; ?>"  <?php if ($value->thumbnail==1) echo "checked"; ?> >  
				 </td>
                <td> <input type="radio"     name="small" value="<?php echo $value->image_id; ?>" 	<?php if ($value->small==1) { echo "checked";} ?>  >       </td>
                <td> <input type="radio"     name="base"	value="<?php echo $value->image_id; ?>"     <?php if ($value->base==1){  echo "checked"; }?>  >   </td>
                <td> <input type="checkbox"  name="gallery[]" value="<?php echo $value->image_id; ?>" <?php if ($value->gallery ==1) { echo "checked";} ?> >     </td>

				<td> <?php echo $value->getStatusText(); ?> </td>	
				<td> <?php echo $value->created_at; ?></td>	
				<td> <?php echo $value->updated_at; ?></td>	
				<td> <input type="checkbox" name="delete[]" value="<?php echo $value->image_id; ?>"> </td>	
			</tr>

			<?php endforeach; ?>
		<?php endif; ?>
			</tbody>
		</table>
 </form>
</body>
</html>