<?php 

$payment = $this->payment;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>EDIT PAYMENT METHOD</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>

	<?php require_once 'view/html/header.phtml'; ?>
	<form action="<?php print_r($urlObject->getUrl("Payment","save",["id"=>$payment->payment_method_id])); ?> " method="POST"> 
		<div class="managediv">
			<span>EDIT PAYMENT METHOD</span>
			<button class="button" type="submit">SAVE</button>
			<button class="button"> <a href="<?php print_r($urlObject->getUrl("Payment","grid",'',TRUE)); ?> ">CANCEL</a></button>
		</div>

		<div>
			<table class="gridtable"> 
				<tr>
					<th>name</th>
					<td> <input type="text" name="payment[name]" value="<?php echo $payment->name; ?>" > </td>
				</tr>
				<tr>
					<th>status</th>
					<?php $statuses = $payment->getTable()->getStatusOptions(); ?>
					<td>
						<select name="payment[status]">
							<?php foreach ($statuses as $key => $value) :?>
								<option value="<?php echo $key; ?>"

									<?php if ($payment->getStatus() == $key) {
										echo "selected";
									}else{
										echo "";
									} ?>

									><?php echo $value; ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
			</table>

		</div>
		<div class="footer">
				footer
		</div>
	</form>

</body>
</html>