<?php 

$products = $this->products;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>product grid</title>
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
</head>
<body>
	<?php require_once 'view/html/header.phtml'; ?>

	<div class="managediv">
		<span class="title">MANAGE PRODUCT</span>
		<button class="button">
			<a href="<?php print_r($urlObject->getUrl(NULL,"add")); ?>">ADD PRODUCT</a>
		</button>
	</div>

	<div> 
		<table class="managetable">
			<thead> 
				<tr>
					<th>PRODUCT ID</th>
					<th>PRODUCT NAME</th>
					<th>COST</th>
					<th>PRICE</th>
					<th>SKU</th>
					<th>STATUS</th>
					<th>QUANTITY</th>
					<th>DISCRIPTION</th>
					<th>COLOR</th>
					<th>MATERIAL</th>
					<th>CREATED AT</th>
					<th>UPDATED AT</th>
					<th>IMAGE</th>
					<th>EDIT</th>
					<th>DELETE</th>
				</tr>
			</thead>
			<tbody>
				<?php if (!$products): ?>
					<tr>
						<td colspan="15">No Record Available.</td>
					</tr>
				<?php else: ?>
					<?php foreach($products as $row): ?>
						<tr>
							<td> <?php echo $row->product_id;  ?> </td>
							<td> <?php echo $row->product_name; ?> </td>
							<td> <?php echo $row->cost; ?> </td>
							<td> <?php echo $row->price; ?> </td>
							<td> <?php echo $row->sku; ?> </td>
							<td> <?php echo $row->getStatusText(); ?> </td>
							<td> <?php echo $row->quantity; ?> </td>
							<td> <?php echo $row->discription; ?> </td>
							<td> <?php echo $row->color; ?> </td>
							<td> <?php echo $row->material; ?> </td>
							<td> <?php echo $row->created_at; ?> </td>
							<td> <?php echo $row->updated_at; ?> </td>
							<td> <a href=" <?php print_r($urlObject->getUrl("product_media","grid",["id"=>$row->product_id])); ?>">IMAGE</a></td>
							<td> <a href="  <?php print_r($urlObject->getUrl("Product","edit",["id"=>$row->product_id])); ?> ">EDIT</a> </td> 
							<td> <a href="<?php print_r($urlObject->getUrl("Product","delete",["id"=>$row->product_id])); ?>">DELETE</a> </td> 
						</tr>
					<?php  endforeach; ?>
				<?php endif; ?>
			</tbody> 
		</table>
	</div>
	<?php require_once 'view/html/footer.phtml'; ?>

</body>
</html>